# docker run -d \
# -p 27017:27017 \
# -e MONGO_INITDB_ROOT_USERNAME=admin \
# -e MONGO_INITDB_ROOT_PASSWORD=admin \
# --net mongo-network \
# --name mongo \
# mongo





version: '3'
services:
  mongodb: mongo # corresponds to --name flag of the above run command
    image: mongo # corresponds to the actual image name with version tag that needs to pulled from container repository
    ports:
      - 27017:27017 # coresponds to -p flag where we specify list of ports to be opened in container with their bindings of host port
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin # corresponds to -e flag of the run command where we specify the list of environment variables